### ISSUE TITLE
dkrcache: too many options for pruneid in testing

### ISSUE THREAD

**Issue by combatopera** [combatopera/lagoon#26]
```
Traceback (most recent call last):
  File "/io/test_dkrcache.py", line 45, in test_force
    self.assertEqual(200, et.run(force = True))
  File "/io/dkrcache/__init__.py", line 123, in run
    outcome = self._outcomeornone(executor, MissHandler, 'Cache hit', force)
  File "/io/dkrcache/__init__.py", line 118, in _outcomeornone
    pruneid, = set(_pruneids()) - before
ValueError: too many values to unpack (expected 1)
```

**Comment by combatopera** [comment]
hog the port to exclude other processes?

**Comment by combatopera** [comment]
fixed by pruning all candidate ids:
* if ours isn't in the set, another process or user must have pruned it
* a user can docker builder prune at any time, so if we prune too much it's not worse than that
